<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Block;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllFinishedBlock()
    {
        $query = $this->createQueryBuilder('block');

        return $query
            ->where($query->expr()->isNotNull('block.hash'))
            ->getQuery()->getResult();
    }

    public function getLastBlock()
    {
        $query = $this->createQueryBuilder('block');
        $subQuery = $this->createQueryBuilder('other_block');

        $blocks = $query
            ->where($query->expr()->not(
                $query->expr()->exists(
                    $subQuery
                        ->where($query->expr()->eq('block.hash', 'other_block.previousHash'))
                    ->getDQL()
                )
            ))
            ->setMaxResults(1)
            ->getQuery()->getResult();

        return count($blocks) !== 0 ? $blocks[0] : null;
    }
}
